--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: redis
  name: redisapp
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: redis
  template: 
    metadata: 
      labels: 
        app: redis
    spec: 
      containers: 
        - 
          image: "redis:4-32bit"
          name: redis
          ports: 
            - 
              containerPort: 6379
          resources: 
            requests: 
              cpu: 200m
              memory: 100Mi
